
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/survey_it
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=anas
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ./target:/app
    networks:
      - app-network


  db:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=survey_it
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=anas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped


volumes:
  postgres_data:

networks:
  app-network: {}